PL/Controllers/CajeroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class CajeroController : Controller
    {
        public ActionResult Cajero()
        {
            ML.Result result = BL.SaldoCajero.GetSaldo();
            ML.SaldoCajero cajero = result.Object as ML.SaldoCajero;
            return View(cajero);
        }
    }
}

PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Controllers/RetiroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class RetiroController : Controller
    {
        // GET: Retiro
        public ActionResult Retiro()
        {
            ML.Result result = BL.Retiro.GetRetiros();
            ML.Retiro retiro = new ML.Retiro();
            retiro.Retiros = result.Objects;
            return View(retiro);
        }

        [HttpGet]
        public ActionResult Form()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Form(int cantidad)
        {
            if(cantidad == 30)
            {
                ViewBag.Mensaje = "No hay denominaciones para cubrir esa cantidad.\n Por favor, ingresa una cantidad diferente.";
                ViewBag.Correct = false;
            }
            else
            {

                ML.Result result = BL.SaldoCajero.GetSaldo();
                ML.SaldoCajero billetesDisponibles = result.Object as ML.SaldoCajero;
                ML.Retiro retiro = ObtenerBilletes(cantidad, billetesDisponibles);

                bool cumple = Verificar(cantidad, retiro);
                if (cumple)
                {
                    ML.Result resultadoOpreacion = BL.Retiro.Retirar(retiro);
                    if (resultadoOpreacion.Correct)
                    {
                        ViewBag.Mensaje = $"Retiro éxitoso. Fecha y hora: {DateTime.Now}. Cantidad: $ {cantidad}";
                        ViewBag.Correct = true;
                    }
                    else
                    {
                        ViewBag.Mensaje = resultadoOpreacion.ErrorMessage;
                        ViewBag.Correct = false;
                    }
                    result = BL.SaldoCajero.GetSaldo();
                    billetesDisponibles = result.Object as ML.SaldoCajero;
                    ValidarExistencias(billetesDisponibles);
                }
                else
                {
                    ViewBag.Mensaje = "No hay demoninaciones disponibles para cubrir esa cantidad. No es posible realizar el retiro.";
                    ViewBag.Correct = false;
                }
            }
            return PartialView("Modal");
        }

        //Método para obtener la cantidad de billetes a retirar
        private ML.Retiro ObtenerBilletes(int cantidad, ML.SaldoCajero saldoCajero)
        {
            ML.Retiro retiro = new ML.Retiro();
            Dictionary<int,int> billetesDisponibles = new Dictionary<int, int>
            {
                { 1000,saldoCajero.Billetes1000 },
                { 500, saldoCajero.Billetes500 },
                { 200, saldoCajero.Billetes200 },
                { 100, saldoCajero.Billetes100 },
                { 50, saldoCajero.Billetes50 },
                { 20, saldoCajero.Billetes20 }
            };
            List<int> billetes = new List<int>(billetesDisponibles.Keys);
            Dictionary<int, int> resultado = new Dictionary<int, int>()
            {
                {1000,0},
                {500,0},
                {200,0},
                {100,0},
                {50,0},
                {20,0},
            };
            foreach(var denominacion in billetes)
            {
                int cantidadDisponible = billetesDisponibles[denominacion];
                int cantidadDeBilletes = Math.Min(cantidad / denominacion, cantidadDisponible);
                if(cantidadDeBilletes > 0)
                {
                    resultado[denominacion] += cantidadDeBilletes;
                    cantidad -= cantidadDeBilletes * denominacion;
                    billetesDisponibles[denominacion] -= cantidadDeBilletes;
                    if(cantidad == 0)
                    {
                        break;
                    }
                }
            }
            retiro.Billetes1000 = resultado[1000];
            retiro.Billetes500 = resultado[500];
            retiro.Billetes200 = resultado[200];
            retiro.Billetes100 = resultado[100];
            retiro.Billetes50 = resultado[50];
            retiro.Billetes20 = resultado[20];
            return retiro;
        }
        //Método para verificar que la cantidad de billetes cubre el total del retiro solicitado.
        private bool Verificar(int cantidad, ML.Retiro retiro)
        {
            bool correct = false;
            int resultado = retiro.Billetes1000 * 1000 + retiro.Billetes500 * 500 + retiro.Billetes200 * 200 + retiro.Billetes100 * 100 + retiro.Billetes50 * 50 + retiro.Billetes20 * 20;
            if(cantidad == resultado) 
            {
                correct = true;
            }
            return correct;
        }
        private ML.SaldoCajero ValidarExistencias(ML.SaldoCajero saldoCajero)
        {
            if(saldoCajero.Billetes1000 == 0)
            {
                ViewBag.Mensaje += " Se han terminado los billetes de 1,000. ";
            }
            if(saldoCajero.Billetes500 == 0)
            {
                ViewBag.Mensaje += " Se han terminado los billetes de 500. ";
            }
            if(saldoCajero.Billetes200 == 0)
            {
                ViewBag.Mensaje += " Se han terminado los billetes de 200. ";
            }
            if(saldoCajero.Billetes100 == 0)
            {
                ViewBag.Mensaje += " Se han terminado los billetes de 100. ";
            }
            if(saldoCajero.Billetes50 == 0)
            {
                ViewBag.Mensaje += " Se han terminado los billetes de 50. ";
            }
            if(saldoCajero.Billetes20  == 0)
            {
                ViewBag.Mensaje += " Se han terminado los billetes de 20. ";
            }
            return saldoCajero;
        }
    }
}

PL/Views/Cajero/Cajero.cshtml
@model ML.SaldoCajero
@{
    ViewBag.Title = "Cajero";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">Cajero</h2>
<hr />
<div class="container">
    <a class="btn btn-success" href="@Url.Action("Form","Retiro")">Retirar</a>
</div>
<hr />
<div class="container">
    <table class="table table-dark table-hover text-center">
        <thead>
            <tr>
                <th>Denominaciones</th>
                <th>Candidad</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1,000</td>
                <td>@Model.Billetes1000</td>
            </tr>
            <tr>
                <td>500</td>
                <td>@Model.Billetes500</td>
            </tr>
            <tr>
                <td>200</td>
                <td>@Model.Billetes200</td>
            </tr>
            <tr>
                <td>100</td>
                <td>@Model.Billetes100</td>
            </tr>
            <tr>
                <td>50</td>
                <td>@Model.Billetes50</td>
            </tr>
            <tr>
                <td>20</td>
                <td>@Model.Billetes20</td>
            </tr>
        </tbody>
    </table>
    <div>
        <label class="text-capitalize">Saldo total: $ @Model.SaldoTotal</label>
    </div>
</div>

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Retiro/Form.cshtml
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";


}

<h2 class="text-center">Realizar un retiro</h2>
<hr />
<style>
    .centrar {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
<div class="centrar">
    <form method="post" class="form" action="~/Retiro/Form">
        <div>
            <label>¿Qué cantidad deseas retirar?</label>
            <input id="cantidad"
                   style="border-width:3px"
                   class="form-control"
                   required
                   name="cantidad"
                   onkeypress="return numbersOnly(event, 'lblError')"
                   onkeyup="TerminarEnCero()" />
        </div>
        <div>
            <label id="lblError"></label><br />
            <label id="lblErrorTerminacion"></label>
            <br />
        </div>
        <div class="centrar">
            <button 
                    id="btnRetirar"
                    disabled 
                    class="btn btn-success" 
                    type="submit">Retirar  <i class="fa-solid fa-hand-holding-dollar"></i></button>
        </div>
    </form>
</div>
<script type="text/javascript">
    function numbersOnly(e, lbl) {
        var charCode = e.keyCode;
        if ((charCode > 47 && charCode < 58) || charCode == 8) {
            $('#' + lbl).text("");
            $('#cantidad').css('border-color', 'green');
            $('#btnRetirar').removeAttr('disabled');
            return true;
        }
        else {
            $('#' + lbl).text("Sólo se admiten números.");
            $('#' + lbl).css('color', 'red');
            $('#cantidad').css('border-color', 'red');
            $("#btnRetirar").attr('disabled', 'disabled');
            return false;
        }
    }
    function TerminarEnCero() {
        var cantidad = $('#cantidad').val();
        const regex = /\d*0$/;
        if (regex.test(cantidad) && parseInt(cantidad) >= 20) {
            $('#lblErrorTerminacion').text("");
            $('#btnRetirar').removeAttr('disabled');
        }
        else {
            $('#lblErrorTerminacion').text("Sólo se admiten cantidades mayores a 20 y con terminación en 0.");
            $('#lblErrorTerminacion').css('color', 'red');
            $("#btnRetirar").attr('disabled', 'disabled');
        }
    }
</script>

PL/Views/Retiro/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @if (ViewBag.Correct)
                {
                    @Html.ActionLink("Continuar", "Retiro", "Retiro", htmlAttributes: new { @class = "btn btn-danger" })
                }
                else
                {
                    @Html.ActionLink("Regresar", "Form", "Retiro", htmlAttributes: new {@class = "btn btn-danger"})
                }

            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Retiro/Retiro.cshtml
@model ML.Retiro 
@{
    ViewBag.Title = "Retiro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">Retiros realizados</h2>
<hr />
<div class="container">
    <table class="table table-dark table-hover text-center">
        <thead>
            <tr>
                <th>Fecha y hora</th>
                <th>1,000</th>
                <th>500</th>
                <th>200</th>
                <th>100</th>
                <th>50</th>
                <th>20</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach(ML.Retiro retiro in Model.Retiros)
            {
                <tr>
                    <td>@retiro.FechaRetiro</td>
                    <td>@retiro.Billetes1000</td>
                    <td>@retiro.Billetes500</td>
                    <td>@retiro.Billetes200</td>
                    <td>@retiro.Billetes100</td>
                    <td>@retiro.Billetes50</td>
                    <td>@retiro.Billetes20</td>
                    <td>$ @retiro.TotalRetiro</td>
                </tr>
            }
        </tbody>
    </table>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body style="background-color:black" class="text-light">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Cajero", "Cajero", "Cajero", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Retiros", "Retiro", "Retiro", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>